"""PDF-ready HTML export for reports — browser print-to-PDF or WeasyPrint."""
from decimal import Decimal
from typing import Optional
from uuid import UUID

from fastapi import APIRouter, Depends, Query
from fastapi.responses import HTMLResponse
import sqlalchemy as sa
from sqlalchemy import select
from sqlalchemy.orm import Session

from database import get_db
from app.models.user import User
from app.models.company import Company
from app.utils.dependencies import get_current_user
from app.utils.report_helpers import loc_filter, base_params

router = APIRouter()

MONTH_NAMES = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
               "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]


def _fmt(v: Decimal) -> str:
    return f"₦{v:,.2f}"


def _html_wrap(title: str, body: str, year: int, company_name: str = "—") -> str:
    from html import escape
    safe_company = escape(company_name)
    return f"""<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<title>{title} — FY {year}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Mulish:wght@400;600;700;800&display=swap');
  body {{ font-family: 'Mulish', sans-serif; font-size: 11px; color: #344767; margin: 24px; }}
  h1 {{ font-size: 18px; color: #1B2A4A; margin-bottom: 2px; }}
  h2 {{ font-size: 13px; color: #5a6580; margin-top: 0; font-weight: 400; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 16px; }}
  th {{ background: #1B2A4A; color: #fff; text-align: left; padding: 6px 10px; font-size: 10px; text-transform: uppercase; letter-spacing: 0.04em; }}
  th.right {{ text-align: right; }}
  td {{ padding: 5px 10px; border-bottom: 1px solid #e9ecef; font-size: 11px; }}
  td.right {{ text-align: right; }}
  td.bold {{ font-weight: 700; }}
  tr.section td {{ background: #17C1E8; color: #fff; font-weight: 800; font-size: 10px; letter-spacing: 0.05em; }}
  tr.total td {{ background: rgba(27,42,74,0.06); font-weight: 800; border-top: 2px solid #1B2A4A; }}
  tr.grand td {{ font-weight: 900; font-size: 13px; }}
  .footer {{ margin-top: 24px; font-size: 9px; color: #6e7a93; text-align: center; }}
  @media print {{ body {{ margin: 0; }} }}
</style>
</head><body>
<h1>{title}</h1>
<h2>Fiscal Year {year} · {safe_company}</h2>
{body}
<div class="footer">Generated by {safe_company} AIS · Powered by Executive Talents Inc.</div>
</body></html>"""


@router.get("/pnl/print", response_class=HTMLResponse)
def pnl_printable(
    year: int = Query(...),
    location_id: Optional[UUID] = Query(None),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    cid = current_user.company_id
    company = (db.execute(
        select(Company).where(Company.id == cid)
    )).scalar_one_or_none()
    company_name = company.name if company else "—"
    params = base_params(cid, year, location_id)
    lf_rev = loc_filter("r", location_id)
    lf_exp = loc_filter("e", location_id)

    # Revenue by account
    rev_result = db.execute(sa.text(f"""
        SELECT a.code, a.name, COALESCE(SUM(r.amount), 0) AS total
        FROM revenue_transactions r JOIN accounts a ON r.account_id = a.id
        WHERE r.company_id = :cid AND r.is_voided = false AND r.fiscal_year = :year{lf_rev}
        GROUP BY a.code, a.name ORDER BY a.code
    """), params)
    rev_lines = [(r.code, r.name, Decimal(str(r.total))) for r in rev_result]
    total_rev = sum(t for _, _, t in rev_lines)

    # Expenses by account
    exp_result = db.execute(sa.text(f"""
        SELECT a.code, a.name, COALESCE(SUM(e.amount), 0) AS total
        FROM expense_transactions e JOIN accounts a ON e.account_id = a.id
        WHERE e.company_id = :cid AND e.is_voided = false AND e.fiscal_year = :year{lf_exp}
        GROUP BY a.code, a.name ORDER BY a.code
    """), params)
    exp_lines = [(r.code, r.name, Decimal(str(r.total))) for r in exp_result]
    total_exp = sum(t for _, _, t in exp_lines)
    net = total_rev - total_exp

    rows = '<table><tr><th>Code</th><th>Account</th><th class="right">Amount (₦)</th></tr>'
    rows += '<tr class="section"><td colspan="3">INCOME</td></tr>'
    for code, name, amt in rev_lines:
        rows += f'<tr><td>{code}</td><td>{name}</td><td class="right">{_fmt(amt)}</td></tr>'
    rows += f'<tr class="total"><td colspan="2">TOTAL INCOME</td><td class="right">{_fmt(total_rev)}</td></tr>'
    rows += '<tr class="section"><td colspan="3">EXPENSES</td></tr>'
    for code, name, amt in exp_lines:
        rows += f'<tr><td>{code}</td><td>{name}</td><td class="right">{_fmt(amt)}</td></tr>'
    rows += f'<tr class="total"><td colspan="2">TOTAL EXPENSES</td><td class="right">{_fmt(total_exp)}</td></tr>'
    label = "NET PROFIT" if net >= 0 else "NET LOSS"
    rows += f'<tr class="grand"><td colspan="2">{label}</td><td class="right">{_fmt(abs(net))}</td></tr>'
    rows += '</table>'

    return _html_wrap("Profit & Loss Statement", rows, year, company_name)


@router.get("/balance-sheet/print", response_class=HTMLResponse)
def balance_sheet_printable(
    year: int = Query(...),
    location_id: Optional[UUID] = Query(None),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    cid = current_user.company_id
    company = (db.execute(
        select(Company).where(Company.id == cid)
    )).scalar_one_or_none()
    company_name = company.name if company else "—"
    lf_rev = loc_filter("r", location_id)
    lf_exp = loc_filter("e", location_id)
    loc_params: dict = {"cid": cid}
    if location_id:
        loc_params["loc_id"] = location_id

    def scalar(sql: str, p: dict) -> Decimal:
        r = db.execute(sa.text(sql), p)
        return Decimal(str(r.scalar_one() or 0))

    all_rev = scalar(f"SELECT COALESCE(SUM(r.amount), 0) FROM revenue_transactions r WHERE r.company_id = :cid AND r.is_voided = false{lf_rev}", loc_params)
    all_exp = scalar(f"SELECT COALESCE(SUM(e.amount), 0) FROM expense_transactions e WHERE e.company_id = :cid AND e.is_voided = false{lf_exp}", loc_params)
    cash = all_rev - all_exp

    caution = scalar(f"SELECT COALESCE(SUM(r.amount), 0) FROM revenue_transactions r JOIN accounts a ON r.account_id = a.id WHERE r.company_id = :cid AND r.is_voided = false AND a.code = '4030'{lf_rev}", loc_params)

    prior_rev = scalar(f"SELECT COALESCE(SUM(r.amount), 0) FROM revenue_transactions r WHERE r.company_id = :cid AND r.is_voided = false AND r.fiscal_year < :year{lf_rev}", {**loc_params, "year": year})
    prior_exp = scalar(f"SELECT COALESCE(SUM(e.amount), 0) FROM expense_transactions e WHERE e.company_id = :cid AND e.is_voided = false AND e.fiscal_year < :year{lf_exp}", {**loc_params, "year": year})
    prior_caution = scalar(f"SELECT COALESCE(SUM(r.amount), 0) FROM revenue_transactions r JOIN accounts a ON r.account_id = a.id WHERE r.company_id = :cid AND r.is_voided = false AND r.fiscal_year < :year AND a.code = '4030'{lf_rev}", {**loc_params, "year": year})
    retained = prior_rev - prior_caution - prior_exp

    cur_rev = scalar(f"SELECT COALESCE(SUM(r.amount), 0) FROM revenue_transactions r WHERE r.company_id = :cid AND r.is_voided = false AND r.fiscal_year = :year{lf_rev}", {**loc_params, "year": year})
    cur_exp = scalar(f"SELECT COALESCE(SUM(e.amount), 0) FROM expense_transactions e WHERE e.company_id = :cid AND e.is_voided = false AND e.fiscal_year = :year{lf_exp}", {**loc_params, "year": year})
    cur_caution = scalar(f"SELECT COALESCE(SUM(r.amount), 0) FROM revenue_transactions r JOIN accounts a ON r.account_id = a.id WHERE r.company_id = :cid AND r.is_voided = false AND r.fiscal_year = :year AND a.code = '4030'{lf_rev}", {**loc_params, "year": year})
    cur_profit = cur_rev - cur_caution - cur_exp

    total_equity = retained + cur_profit

    rows = '<table><tr><th>Item</th><th class="right">Amount (₦)</th></tr>'
    rows += '<tr class="section"><td colspan="2">ASSETS</td></tr>'
    rows += f'<tr><td>Cash & Bank</td><td class="right">{_fmt(cash)}</td></tr>'
    rows += f'<tr class="total"><td>TOTAL ASSETS</td><td class="right">{_fmt(cash)}</td></tr>'
    rows += '<tr class="section"><td colspan="2">LIABILITIES</td></tr>'
    rows += f'<tr><td>Caution Deposits Payable</td><td class="right">{_fmt(caution)}</td></tr>'
    rows += f'<tr class="total"><td>TOTAL LIABILITIES</td><td class="right">{_fmt(caution)}</td></tr>'
    rows += '<tr class="section"><td colspan="2">EQUITY</td></tr>'
    rows += f'<tr><td>Retained Earnings (prior to FY {year})</td><td class="right">{_fmt(retained)}</td></tr>'
    rows += f'<tr><td>Net Profit / (Loss) FY {year}</td><td class="right">{_fmt(cur_profit)}</td></tr>'
    rows += f'<tr class="total"><td>TOTAL EQUITY</td><td class="right">{_fmt(total_equity)}</td></tr>'
    rows += f'<tr class="grand"><td>TOTAL LIABILITIES + EQUITY</td><td class="right">{_fmt(caution + total_equity)}</td></tr>'
    rows += '</table>'

    return _html_wrap("Balance Sheet", rows, year, company_name)
